---
title: "sars_cov_2_monocle"
output: html_notebook
---
```{r}
library(monocle3)
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(ggplot2)
library(patchwork)
library(magrittr)
```
## Monocle3 pre-process and UMAP
```{r}
alive_integrated <- readRDS("~/sars-cov-2/alive_integrated.rds")
cds <- as.cell_data_set(alive_integrated)
cds <- preprocess_cds(cds, num_dim = 30)
cds <- reduce_dimension(cds)
cds <- cluster_cells(cds)
cds <- learn_graph(cds)


unlabelled <- plot_cells(cds)
ggsave("./monocle3_unlabelled_clusters.pdf")
labelled <- plot_cells(cds, color_cells_by = "cell_type", show_trajectory_graph = FALSE) + theme(legend.position = "right")
plot_cells(cds, color_cells_by = "partition")
ggsave("./monocle2_partitions.pdf")
integrated.sub <- subset(as.Seurat(cds, assay = NULL), monocle3_partitions == 1)
```


## Learn graph
```{r}
cds <- as.cell_data_set(integrated.sub)
cds <- learn_graph(cds)
plot_cells(cds, label_groups_by_cluster = FALSE, label_leaves = FALSE, label_branch_points = FALSE)

ggsave("alive_monocle3_cds_branch.pdf", width = 7, height = 7)
```


## Pseudotime
```{r}
get_earliest_principal_node <- function(cds, time_bin ="SARS_CoV_2_3dpi"){
  for(partition_id in unique(partitions(cds))){

    partition_cell_ids <- which(partitions(cds) == partition_id)
    temp_cds <- cds[ , partition_cell_ids]

    cell_ids <- which(colData(temp_cds)[, "orig.ident"] == time_bin)

    closest_vertex <- temp_cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
    closest_vertex <- as.matrix(closest_vertex[colnames(temp_cds), ])
    root_pr_node <- igraph::V(principal_graph(temp_cds)[["UMAP"]])$name[as.numeric(names
    (which.max(table(closest_vertex[cell_ids,]))))]

    if( partition_id == unique(partitions(cds))[1]){
        root_pr_nodes <- root_pr_node
      } else{
        root_pr_nodes <- c(root_pr_nodes, root_pr_node)
      }
    }
  root_pr_nodes
}
cds <- order_cells(cds, root_pr_nodes=get_earliest_principal_node(cds))

plot_cells(cds, 
           color_cells_by = "pseudotime", 
           label_cell_groups = FALSE, 
           label_leaves = FALSE, 
           label_branch_points = FALSE) + 
  theme(legend.key.size = unit(1, 'cm'),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        axis.title = element_text(size = 10))
ggsave("./monocle3_sars_cov_2_pseudotime.pdf", height = 8, width = 12)
```
